export const projectData = [
  {
    slug: "private-residence-gurgaon",
    title: "Private Residence, Gurgaon",
    category: "Residential Architecture",
    isColorByDefault: true,
    description: "A contemporary residence balancing open social spaces with private retreats. Designed with a neutral palette and natural stone to create a timeless, light-filled home.",
    images: ["/projects/p1.png", "/projects/p2.png", "/projects/p3.png", "/projects/p4.png", "/projects/p5.png", "/projects/p6.png"],
    year: "2023",
    location: "Gurgaon, Haryana",
    service: "Architecture & Interiors",
  },
  {
    slug: "boutique-office-space",
    title: "Boutique Office Space",
    category: "Commercial Interiors",
    isColorByDefault: true,
    description: "A high-performance workspace crafted for executive comfort. Focused on refined spatial planning and custom joinery to maximize natural light.",
    images: ["/projects/p3.png", "/projects/p1.png", "/projects/p2.png", "/projects/p4.png", "/projects/p5.png", "/projects/p6.png"],
    year: "2024",
    location: "Vibhuti Khand, Luckow",
    service: "Commercial Design",
  },
  {
    slug: "luxury-apartment-interior",
    title: "Luxury Apartment Interior",
    category: "Interior Design",
    isColorByDefault: true,
    description: "A calm, elegant interior emphasizing texture over color. A rich sensory experience created through bespoke furniture and layered lighting.",
    images: ["/projects/p5.png", "/projects/p1.png", "/projects/p2.png", "/projects/p3.png", "/projects/p4.png", "/projects/p6.png"],
    year: "2023",
    location: "Gomti Nagar, Luckow",
    service: "Interior Design",
  },
  {
    slug: "turnkey-villa-project",
    title: "Turnkey Villa Project",
    category: "Design & Execution",
    isColorByDefault: true,
    description: "A complete villa delivered from concept to completion. Bespoke structural framework paired with curated art and decor for a seamless lifestyle.",
    images: ["/projects/p2.png", "/projects/p1.png", "/projects/p3.png", "/projects/p4.png", "/projects/p5.png", "/projects/p6.png"],
    year: "2024",
    location: "Lucknow, Uttar Pradesh",
    service: "Turnkey Architecture",
  },
  {
    slug: "minimalist-zen-corridor",
    title: "Minimalist Zen Corridor",
    category: "Architectural Detail",
    isColorByDefault: true,
    description: "An exploration of transitional spaces defined by light and shadow. Vertical wood slats and raw concrete create a meditative, rhythmic atmosphere.",
    images: ["/projects/p4.png", "/projects/p1.png", "/projects/p2.png", "/projects/p3.png", "/projects/p5.png", "/projects/p6.png"],
    year: "2024",
    location: "Noida, NCR",
    service: "Spatial Curation",
  },
  {
    slug: "glass-steel-abstraction",
    title: "Glass & Steel Abstraction",
    category: "Futuristic Design",
    isColorByDefault: true,
    description: "A study in transparency and structural rhythm. Utilizing custom steel lattice to optimize performance while maintaining a crystalline aesthetic.",
    images: ["/projects/p6.png", "/projects/p1.png", "/projects/p2.png", "/projects/p3.png", "/projects/p4.png", "/projects/p5.png"],
    year: "2025",
    location: "New Delhi, India",
    service: "Facade Engineering",
  },
];
